- name: create ec2 and route 53
  hosts: local # hostes ani vunte error vastundi 
  connection: local
  vars:
    ami_id: ami-09c813fb71547fc4f
    sg_id: sg-05184d3f3e9b3610f # replace with your SG ID
    zone_id: "Z0508801ITHFU9ARNA74" # replace with your ID
    domain_name: "dsoaws.fun"
    # we can pass instances through command line using -e     ... so everytime vachhi add chesukoni run cheyakunda intance ni by cmd tho run cretae cheyabchu 
    
    # instances:
    # - mongodb
    # - redis 
    # - mysql 
    # - rabbitmq
  tasks:
  - name: create ec2 instance 
    amazon.aws.ec2_instance:
      name: "{{ item }}" # this the key for reffer instance
      instance_type: t3.micro
      security_group: "{{ sg_id }}"
      image_id: "{{ ami_id }}"

      tags: # this is used for visible name for our understanding purpose
        Name: "{{ item }}"  # ietm enduku ante instance aa name tho vudo aa name tho manaki visible authunhdi 
    loop: "{{ instances }}" #  so here intially instance ani vudi -- error fatal: [localhost]: FAILED! => {"msg": "'instances' is undefined. 'instances' is undefined"}
    register: ec2_output # manam istum name 
  
  # - name: print the ec2_output
  #   ansible.builtin.debug:
  #     msg: "{{ ec2_output }}"

# #  [ ec2-user@ip-172-31-76-65 ~/ansible-roboshop ]$ pip3.9 install botocore boto3 -- so idi install cheste ansible can connect 

# for testing purpose we use the below

  # - name: print public_ip
  #   ansible.builtin.debug: 
  #     msg: "{{ item.instances[0].public_ip_address }}"
  #   loop: "{{ ec2_output.results }}"

  # - name: print private_ip
  #   ansible.builtin.debug: 
  #     msg: "{{ item.instances[0].private_ip_address }}"
  #   loop: "{{ ec2_output.results }}"

#   #SO HERE SEPARATE GA PUBLIC AND PRIVATE IP DISPLAY AVUTHAI


  
  - name: create route53 record
    amazon.aws.route53:
      state: present
      zone: "{{ domain_name }}"
      record: "{{ item.item }}.{{ domain_name }}" # mongodb.daws86s.fun
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      overwrite: true # so ikkada present ayyi vunte dhanni replace ayyi new ga update avuthundi 
    loop: "{{ ec2_output.results }}"

  # # we are creating one record with public only for frontend
  # - name: create route53 record for frontend
  #   amazon.aws.route53:
  #     state: present
  #     zone: "{{ domain_name }}"
  #     record: "{{ domain_name }}" # daws86s.fun
  #     type: A
  #     ttl: 1
  #     value: "{{ item.instances[0].public_ip_address }}"
  #     overwrite: true
  #   when: item.item == "frontend"
  #   loop: "{{ ec2_output.results }}"