- name: set up Backend for Expensive
  hosts: exbk
  become: yes
  tasks:
  - name: Disabling NODEJS 
    ansible.builtin.command: dnf module disable nodejs -y
  
  - name: Enabling NODEJS20
    ansible.builtin.command: dnf module enable nodejs:20 -y

  - name: Installing nodejs 
    ansible.builtin.package:
      name: nodejs
      state: present

  - name: Create expense user
    ansible.builtin.user:
      name: expense
      shell: /bin/bash
      state: present

  - name: remove app directory
    ansible.builtin.file: # type in google ansible create directory module  ----https://docs.ansible.com/projects/ansible/latest/collections/ansible/builtin/file_module.html
      path: /app
      state: absent

  - name: create app directory
    ansible.builtin.file:
      state: directory # present ani kuda ivvachu 
      path: /app

  - name: Removing backend.zip file
    ansible.builtin.file:
      path: /tmp/backend.zip
      state: absent
  
  # - name: create backend.zip file directory
  #   ansible.builtin.file:
  #     state: directory
  #     path: /tmp/backend.zip

  - name: Download Expense Backend
    ansible.builtin.get_url:
      url: https://expense-joindevops.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
      dest: /tmp/backend.zip

  - name: Extract Backend
    ansible.builtin.unarchive:
      src: /tmp/backend.zip
      dest: /app
      remote_src: yes

  - name: install dependencies
    community.general.npm: # ansible node npm --- https://docs.ansible.com/projects/ansible/latest/collections/community/general/npm_module.html
      path: /app

  - name: Copying backend service file
    ansible.builtin.copy:
      src: backend.service
      dest: /etc/systemd/system

  # - name: daemon reload enable and start
  #   ansible.builtin.systemd_service:
  #     name: backend
  #     enabled: true
  #     state: started
  #     daemon_reload: true

  # - name: Set up service files
  #   ansible.builtin.service:
  #     name: backend
  #     state: started
  #     enabled: yes

  - name: Installing mysql clinet server
    ansible.builtin.package:
      name: mysql
      state: present
  
  - name: Install PyMySQL
    ansible.builtin.pip:
      name: PyMySQL
      state: present

  - name: Load MySQL schema
    ansible.builtin.shell: mysql -h exdb.dsoaws.fun -uroot -pExpenseApp@1 < /app/schema/backend.sql

  
  - name: daemon reload enable and start
    ansible.builtin.systemd_service:
      name: backend
      enabled: true
      state: started
      daemon_reload: true

  - name: Set up service files
    ansible.builtin.service:
      name: backend
      state: started
      enabled: yes
  

  