- name: setup mongodb
  hosts: mongodb
  become: yes
  tasks: 
  - name: copy mongodb repo # our understand name
    ansible.builtin.copy:  # take from doc for excute the cmd URL IS ----  https://docs.ansible.com/projects/ansible/latest/collections/ansible/builtin/copy_module.html
    # we need to give one tab space
      src: mongo.repo 
      dest: /etc/yum.repos.d/mongo.repo
    # here we have one dig that is ansible-roboshop 15:00 min class 25 
    # gathering facts step success ite we can able to conect .........
  - name: install mongodb server
    ansible.builtin.package: # URL iS: https://docs.ansible.com/projects/ansible/latest/collections/ansible/builtin/package_module.html
      name: mongodb-org 
      state: present

  # - name: Start service mongod,if not started
  #   ansible.builtin.service: # https://docs.ansible.com/projects/ansible/latest/collections/ansible/builtin/service_module.html
  #     name: mongod
  #     state: started
  #     enabled: yes
  # so idhi lst lo rasam
    
  - name: allow remote connections
    ansible.builtin.replace: # https://docs.ansible.com/projects/ansible/latest/collections/ansible/builtin/replace_module.html
      path: /etc/mongod.conf
      regexp: '127.0.0.1'
      replace: '0.0.0.0'


  - name: Start service mongod,if not started
    ansible.builtin.service: # https://docs.ansible.com/projects/ansible/latest/collections/ansible/builtin/service_module.html
      name: mongod
      state: started
      enabled: yes